const basketTypes = {
    LIST_BASKET_ITEMS: 'LIST_BASKET_ITEMS',
    LIST_BASKET_ITEMS_PENDING: 'LIST_BASKET_ITEMS_PENDING',
    LIST_BASKET_ITEMS_FULFILLED: 'LIST_BASKET_ITEMS_FULFILLED',
    LIST_BASKET_ITEMS_REJECTED: 'LIST_BASKET_ITEMS_REJECTED',

    PURCHASE_BASKET: 'PURCHASE_BASKET',
    PURCHASE_BASKET_PENDING: 'PURCHASE_BASKET_PENDING',
    PURCHASE_BASKET_FULFILLED: 'PURCHASE_BASKET_FULFILLED',
    PURCHASE_BASKET_REJECTED: 'PURCHASE_BASKET_REJECTED',

    DELETE_BASKET: 'DELETE_BASKET',
    DELETE_BASKET_PENDING: 'DELETE_BASKET_PENDING',
    DELETE_BASKET_FULFILLED: 'DELETE_BASKET_FULFILLED',
    DELETE_BASKET_REJECTED: 'DELETE_BASKET_REJECTED',

    UPDATE_BASKET: 'UPDATE_BASKET',
    UPDATE_BASKET_PENDING: 'UPDATE_BASKET_PENDING',
    UPDATE_BASKET_FULFILLED: 'UPDATE_BASKET_FULFILLED',
    UPDATE_BASKET_REJECTED: 'UPDATE_BASKET_REJECTED',
};

export default basketTypes;
