const productTypes = {
    LIST_PRODUCTS: 'LIST_PRODUCTS',
    LIST_PRODUCTS_PENDING: 'LIST_PRODUCTS_PENDING',
    LIST_PRODUCTS_FULFILLED: 'LIST_PRODUCTS_FULFILLED',
    LIST_PRODUCTS_REJECTED: 'LIST_PRODUCTS_REJECTED',

    CREATE_PRODUCT: 'CREATE_PRODUCT',
    CREATE_PRODUCT_PENDING: 'CREATE_PRODUCT_PENDING',
    CREATE_PRODUCT_FULFILLED: 'CREATE_PRODUCT_FULFILLED',
    CREATE_PRODUCT_REJECTED: 'CREATE_PRODUCT_REJECTED',

    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_PENDING: 'DELETE_PRODUCT_PENDING',
    DELETE_PRODUCT_FULFILLED: 'DELETE_PRODUCT_FULFILLED',
    DELETE_PRODUCT_REJECTED: 'DELETE_PRODUCT_REJECTED',

    EDIT_PRODUCT: 'EDIT_PRODUCT',
    EDIT_PRODUCT_PENDING: 'EDIT_PRODUCT_PENDING',
    EDIT_PRODUCT_FULFILLED: 'EDIT_PRODUCT_FULFILLED',
    EDIT_PRODUCT_REJECTED: 'EDIT_PRODUCT_REJECTED',

    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_PENDING: 'GET_PRODUCT_PENDING',
    GET_PRODUCT_FULFILLED: 'GET_PRODUCT_FULFILLED',
    GET_PRODUCT_REJECTED: 'GET_PRODUCT_REJECTED',
};

export default productTypes;
