const settingsTypes = {
    CHECK_BACKEND_HEALTH: 'CHECK_BACKEND_HEALTH',
    CHECK_BACKEND_HEALTH_PENDING: 'CHECK_BACKEND_HEALTH_PENDING',
    CHECK_BACKEND_HEALTH_FULFILLED: 'CHECK_BACKEND_HEALTH_FULFILLED',
    CHECK_BACKEND_HEALTH_REJECTED: 'CHECK_BACKEND_HEALTH_REJECTED',
};

export default settingsTypes;
